### ISSUE TITLE
Not MVVM

### ISSUE THREAD

**Issue by ispha** [yasuohasegawa/Swift-MVVM-Test#1]
In MVVM view should know nothing about the model . Here you are taking an instance from the model in the view !

**Comment by ispha** [comment]
In fact you have  the bindAndFire , which is now applied on the property of the protocol which is in its role a model so you no longer need a new model , you're in bindAndFire , use new values directly with the magic $0 after unwound self !

**Comment by yasuohasegawa** [comment]
Thank you for letting me know. Yes, you are right. I've removed model instance from view.
